apiVersion: torrentdam.github.com/v1
kind: Torrent
metadata:
  name: example-torrent
  namespace: default
spec:
  infoHash: c8295ce630f2064f08440db1534e4992cfe4862a
  pvcName: movies
  dhtNode: dht.transmissionbt.com:6881
